location: .gitman
sources:
  - repo: https://github.com/Gremsy/gSDK.git 
    name: gSDK 
    rev: master 
    type: git
    params:
    sparse_paths:
      - 
    links:
      - source: ''
        target: src/gSDK
